name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
  merge_group:

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install

  build:
    name: Build and lint packages
    needs: install
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm lint
      - run: pnpm lint:copyright
      - run: pnpm run build --filter="{./packages/*}..."

  e2e:
    name: Run e2e tests
    needs: install
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build --filter=e2e

      - name: Run Playwright tests
        run: pnpm run test --filter=e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-report
          path: testing/e2e/playwright-report/
          retention-days: 30
